# Generated by Django 4.2.3 on 2023-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('imdb', models.IntegerField()),
            ],
        ),
    ]
